name: Démonstration CI

on: push

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Etape 1 - Initialisation"
      - run: echo "Etape 2 - Récupération du code"
      - run: echo "Etape 3 - Build"
      - run: echo "Etape 4 - Tests"
      - run: echo "Etape 5 - Packaging"
      - run: echo "Etape 6 - Fin du pipeline"
      - run: echo "Complete job"