name: Démonstration CI

on: push

jobs:
  init:
    runs-on: ubuntu-latest

    env:
      STEP1: "Workflow - initialisation"

    steps:
      - name: Etape 1 - Initialisation
        run: |
          echo "Etape 1"
          echo "STEP1=$STEP1"

      - name: Etape 2 - Récupération du code
        run: echo "STEP2= ${{ vars.STEP2 }}"

      - name: Etape 3 - Build
        run: echo "STEP3= ${{ secrets.STEP3 }}"

      - name: Etape 4 - Tests
        run: echo "Etape 4"

      - name: Etape 5 - Packaging
        run: echo "Etape 5"

      - name: Etape 6 - Fin du pipeline
        run: echo "Etape 6"

  eine-job:
    runs-on: self-hosted
    steps:
      - name: Etape 1 - Initialisation
        run: echo "$(hostname)"
